apiVersion: v1
kind: Service
metadata:
  name: {{ include "brownbag-kubernetes-bootcamp.fullname" . }}
  labels:
    {{- include "brownbag-kubernetes-bootcamp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30002
      {{- end }}
  selector:
    {{- include "brownbag-kubernetes-bootcamp.selectorLabels" . | nindent 4 }}
